language: python
os: [
  "linux"
]

dist: "xenial"

services:
  - mongodb

python:
  - "3.7"

cache: pip

install:
  - pip install flake8 pydocstyle codecov
  - python setup.py install


before_script:
  - python -m spacy download en

script:
  - flake8
  - pydocstyle
  - coverage run -m unittest discover

after_success:
  - codecov -t 991386f7-211f-4134-993a-d94a6dba361f

branches:
  only:
    - staging
    - master
