language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install flake8 pydocstyle
  - pip install -r requirements.txt

# Run tests
script:
  - flake8
  - pydocstyle
  - python -m unittest discover

branches:
  only:
    - staging

notifications:
    slack: usfd-nlp:79cXz6zwLt3ApzgjxKx7Yvdx
