language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install flake8 pydocstyle
  - pip install -r requirements.txt

before_script:
  - python -m spacy download en
  - python -m nltk.downloader popular

script:
  - flake8
  - pydocstyle
  - python -m unittest discover

branches:
  only:
    - staging
