language: python
os: [
  "linux"
]

dist: "xenial"

env:
  global:
    - TQDM_DISABLE=True

services:
  - mongodb

python:
  - "3.7"

cache: pip

install:
  - pip install flake8 pydocstyle codecov spacy
  - pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
  - python setup.py install

before_script:
  - python -m spacy download en

script:
  - flake8 --per-file-ignores=mlearn/base.py:F401
  - pydocstyle
  - coverage run -m unittest discover

after_success:
  - codecov -t 991386f7-211f-4134-993a-d94a6dba361f

branches:
  only:
    - staging
    - master
