language: python

services:
  - mongodb

python:
  - "3.7"

cache: pip

install:
  - pip install flake8 pydocstyle
  - pip install -r requirements.txt

before_script:
  - python -m spacy download en
  - python -m nltk.downloader punkt stopwords

script:
  - flake8
  - pydocstyle
  - python -m unittest discover

branches:
  only:
    - staging
    - master

notifications:
    slack: usfd-nlp:79cXz6zwLt3ApzgjxKx7Yvdx
